# Solo IntelliSense local: no modifica los .c ni la compilacion en WSL.
$ErrorActionPreference = 'Stop'
$taskConfig = Join-Path $PSScriptRoot 'c_cpp_properties.json'
if (Test-Path -LiteralPath $taskConfig) { throw 'La configuracion ya existe; revisala antes de volver a ejecutar.' }
$taskDir = Join-Path $PSScriptRoot 'mpi-intellisense'
New-Item -ItemType Directory -Path $taskDir -Force | Out-Null
$taskHeader = '"#ifndef MPI_EDITOR_ONLY_H\n#define MPI_EDITOR_ONLY_H\n#if !defined(__INTELLISENSE__) || !defined(_WIN32)\n#error \"Solo para IntelliSense Windows. Compila con MPI real en WSL.\"\n#endif\n/* Declaraciones educativas, no representan la ABI de MPI real. */\ntypedef int MPI_Comm;\ntypedef int MPI_Datatype;\ntypedef int MPI_Op;\ntypedef struct { int MPI_SOURCE, MPI_TAG, MPI_ERROR; } MPI_Status;\n#define MPI_COMM_WORLD ((MPI_Comm)0)\n#define MPI_INT ((MPI_Datatype)1)\n#define MPI_SUM ((MPI_Op)1)\n#define MPI_MAX ((MPI_Op)2)\n#define MPI_MIN ((MPI_Op)3)\n#define MPI_STATUS_IGNORE ((MPI_Status *)0)\nint MPI_Init(int *, char ***);\nint MPI_Finalize(void);\nint MPI_Comm_rank(MPI_Comm, int *);\nint MPI_Comm_size(MPI_Comm, int *);\nint MPI_Send(const void *, int, MPI_Datatype, int, int, MPI_Comm);\nint MPI_Recv(void *, int, MPI_Datatype, int, int, MPI_Comm, MPI_Status *);\nint MPI_Abort(MPI_Comm, int);\nint MPI_Bcast(void *, int, MPI_Datatype, int, MPI_Comm);\nint MPI_Reduce(const void *, void *, int, MPI_Datatype, MPI_Op, int, MPI_Comm);\nint MPI_Allreduce(const void *, void *, int, MPI_Datatype, MPI_Op, MPI_Comm);\nint MPI_Gather(const void *, int, MPI_Datatype, void *, int, MPI_Datatype, int, MPI_Comm);\nint MPI_Gatherv(const void *, int, MPI_Datatype, void *, const int *, const int *, MPI_Datatype, int, MPI_Comm);\nint MPI_Scatter(const void *, int, MPI_Datatype, void *, int, MPI_Datatype, int, MPI_Comm);\nint MPI_Scatterv(const void *, const int *, const int *, MPI_Datatype, void *, int, MPI_Datatype, int, MPI_Comm);\nint MPI_Reduce_scatter(const void *, void *, const int *, MPI_Datatype, MPI_Op, MPI_Comm);\nint MPI_Barrier(MPI_Comm);\nint MPI_Scan(const void *, void *, int, MPI_Datatype, MPI_Op, MPI_Comm);\n#endif\n"' | ConvertFrom-Json
[System.IO.File]::WriteAllText((Join-Path $taskDir 'mpi.h'), $taskHeader, [System.Text.UTF8Encoding]::new($false))
$taskJson = '"{\n    \"configurations\": [\n        {\n            \"name\": \"Win32\",\n            \"compilerPath\": \"C:/MinGW/bin/gcc.exe\",\n            \"intelliSenseMode\": \"windows-gcc-x86\",\n            \"includePath\": [\n                \"${workspaceFolder}/.vscode/mpi-intellisense\",\n                \"${workspaceFolder}\"\n            ],\n            \"cStandard\": \"c99\"\n        },\n        {\n            \"name\": \"Linux\",\n            \"compilerPath\": \"/usr/bin/mpicc\",\n            \"intelliSenseMode\": \"linux-gcc-x64\",\n            \"includePath\": [\n                \"${workspaceFolder}\"\n            ],\n            \"cStandard\": \"c99\"\n        }\n    ],\n    \"version\": 4\n}"' | ConvertFrom-Json
[System.IO.File]::WriteAllText($taskConfig, $taskJson, [System.Text.UTF8Encoding]::new($false))
Write-Output 'Configuracion local creada: selecciona Win32 en VS Code.'
